import { describe, expect, it } from "vitest";
import * as runtime from "./index.js";

const retainedRuntimeValues = [
  "assertNever",
  "assertValidContext",
  "baseTypeSymbols",
  "buildArray",
  "buildArrayBoolean",
  "buildArrayNull",
  "buildArrayNumber",
  "buildArrayString",
  "buildBoolean",
  "buildNull",
  "buildNumber",
  "buildRecord",
  "buildString",
  "combine",
  "combineBooleanOp",
  "combineNumberOp",
  "combineStringOp",
  "cond",
  "convertValue",
  "createEmptySequenceError",
  "createFunctionExecutionError",
  "createInvalidValueError",
  "createMissingDefinitionError",
  "createMissingDependencyError",
  "createMissingValueError",
  "ctx",
  "executeGraph",
  "executeGraphSafe",
  "getCombineFnReturnType",
  "hasTag",
  "isArray",
  "isBoolean",
  "isBuilderValidationError",
  "isFuncCondition",
  "isGraphExecutionError",
  "isNull",
  "isNumber",
  "isPure",
  "isPureBoolean",
  "isPureNull",
  "isPureNumber",
  "isPureString",
  "isRecord",
  "isString",
  "isTypedArray",
  "isValidContext",
  "isValueBuilderError",
  "isValueCondition",
  "nullReasonSubSymbols",
  "pipe",
  "recordGet",
  "recordSet",
  "ref",
  "unaryBooleanOp",
  "unaryNumberOp",
  "unaryStringOp",
  "val",
  "validateContext",
] as const;

describe("public runtime API", () => {
  it("retains every documented runtime value export", () => {
    expect(new Set(Object.keys(runtime))).toEqual(new Set(retainedRuntimeValues));
  });
});
