// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: turnout-model.proto

// Package turnout.model.v1 is the single source of truth for the JSON contract
// emitted by the Go converter (-format json) and consumed by the TypeScript
// scene-runner. Changing this file and running `buf generate` from the repo
// root regenerates both the Go and TypeScript types automatically.

package turnoutpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TurnModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *StateModel            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Scenes        []*SceneBlock          `protobuf:"bytes,2,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Routes        []*RouteModel          `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnModel) Reset() {
	*x = TurnModel{}
	mi := &file_turnout_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnModel) ProtoMessage() {}

func (x *TurnModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnModel.ProtoReflect.Descriptor instead.
func (*TurnModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{0}
}

func (x *TurnModel) GetState() *StateModel {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TurnModel) GetScenes() []*SceneBlock {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *TurnModel) GetRoutes() []*RouteModel {
	if x != nil {
		return x.Routes
	}
	return nil
}

type StateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*NamespaceModel      `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateModel) Reset() {
	*x = StateModel{}
	mi := &file_turnout_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateModel) ProtoMessage() {}

func (x *StateModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateModel.ProtoReflect.Descriptor instead.
func (*StateModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{1}
}

func (x *StateModel) GetNamespaces() []*NamespaceModel {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type NamespaceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*FieldModel          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceModel) Reset() {
	*x = NamespaceModel{}
	mi := &file_turnout_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceModel) ProtoMessage() {}

func (x *NamespaceModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceModel.ProtoReflect.Descriptor instead.
func (*NamespaceModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceModel) GetFields() []*FieldModel {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FieldModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is one of: "number" | "str" | "bool" | "arr<number>" | "arr<str>" | "arr<bool>"
	Type          string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldModel) Reset() {
	*x = FieldModel{}
	mi := &file_turnout_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldModel) ProtoMessage() {}

func (x *FieldModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldModel.ProtoReflect.Descriptor instead.
func (*FieldModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{3}
}

func (x *FieldModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SceneBlock struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntryActions []string               `protobuf:"bytes,2,rep,name=entry_actions,json=entryActions,proto3" json:"entry_actions,omitempty"`
	// next_policy is one of: "first-match" | "all-match". Absent means first-match.
	NextPolicy    *string        `protobuf:"bytes,3,opt,name=next_policy,json=nextPolicy,proto3,oneof" json:"next_policy,omitempty"`
	Actions       []*ActionModel `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneBlock) Reset() {
	*x = SceneBlock{}
	mi := &file_turnout_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneBlock) ProtoMessage() {}

func (x *SceneBlock) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneBlock.ProtoReflect.Descriptor instead.
func (*SceneBlock) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{4}
}

func (x *SceneBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SceneBlock) GetEntryActions() []string {
	if x != nil {
		return x.EntryActions
	}
	return nil
}

func (x *SceneBlock) GetNextPolicy() string {
	if x != nil && x.NextPolicy != nil {
		return *x.NextPolicy
	}
	return ""
}

func (x *SceneBlock) GetActions() []*ActionModel {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ActionModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compute       *ComputeModel          `protobuf:"bytes,2,opt,name=compute,proto3" json:"compute,omitempty"`
	Prepare       []*PrepareEntry        `protobuf:"bytes,3,rep,name=prepare,proto3" json:"prepare,omitempty"`
	Merge         []*MergeEntry          `protobuf:"bytes,4,rep,name=merge,proto3" json:"merge,omitempty"`
	Publish       []string               `protobuf:"bytes,5,rep,name=publish,proto3" json:"publish,omitempty"`
	Next          []*NextRuleModel       `protobuf:"bytes,6,rep,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionModel) Reset() {
	*x = ActionModel{}
	mi := &file_turnout_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionModel) ProtoMessage() {}

func (x *ActionModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionModel.ProtoReflect.Descriptor instead.
func (*ActionModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{5}
}

func (x *ActionModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionModel) GetCompute() *ComputeModel {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *ActionModel) GetPrepare() []*PrepareEntry {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *ActionModel) GetMerge() []*MergeEntry {
	if x != nil {
		return x.Merge
	}
	return nil
}

func (x *ActionModel) GetPublish() []string {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *ActionModel) GetNext() []*NextRuleModel {
	if x != nil {
		return x.Next
	}
	return nil
}

type ComputeModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// root is the binding name whose resolved value is the action's compute output.
	Root          string     `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Prog          *ProgModel `protobuf:"bytes,2,opt,name=prog,proto3" json:"prog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeModel) Reset() {
	*x = ComputeModel{}
	mi := &file_turnout_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeModel) ProtoMessage() {}

func (x *ComputeModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeModel.ProtoReflect.Descriptor instead.
func (*ComputeModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{6}
}

func (x *ComputeModel) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ComputeModel) GetProg() *ProgModel {
	if x != nil {
		return x.Prog
	}
	return nil
}

type ProgModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bindings      []*BindingModel        `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgModel) Reset() {
	*x = ProgModel{}
	mi := &file_turnout_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgModel) ProtoMessage() {}

func (x *ProgModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgModel.ProtoReflect.Descriptor instead.
func (*ProgModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{7}
}

func (x *ProgModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgModel) GetBindings() []*BindingModel {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type BindingModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is a FieldTypeStr: "number" | "str" | "bool" | "arr<number>" | "arr<str>" | "arr<bool>"
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Exactly one of value or expr is present.
	Value *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expr  *ExprModel      `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
	// ext_expr carries the structured source expression for #if/#case/#pipe bindings.
	// Used by the HCL emitter to reproduce the original form. Ignored by the runtime.
	ExtExpr       *LocalExprModel `protobuf:"bytes,5,opt,name=ext_expr,json=extExpr,proto3" json:"ext_expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingModel) Reset() {
	*x = BindingModel{}
	mi := &file_turnout_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingModel) ProtoMessage() {}

func (x *BindingModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingModel.ProtoReflect.Descriptor instead.
func (*BindingModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{8}
}

func (x *BindingModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BindingModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BindingModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BindingModel) GetExpr() *ExprModel {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *BindingModel) GetExtExpr() *LocalExprModel {
	if x != nil {
		return x.ExtExpr
	}
	return nil
}

type ExprModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of combine, pipe, or cond is present.
	Combine       *CombineExpr `protobuf:"bytes,1,opt,name=combine,proto3" json:"combine,omitempty"`
	Pipe          *PipeExpr    `protobuf:"bytes,2,opt,name=pipe,proto3" json:"pipe,omitempty"`
	Cond          *CondExpr    `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExprModel) Reset() {
	*x = ExprModel{}
	mi := &file_turnout_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprModel) ProtoMessage() {}

func (x *ExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExprModel.ProtoReflect.Descriptor instead.
func (*ExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{9}
}

func (x *ExprModel) GetCombine() *CombineExpr {
	if x != nil {
		return x.Combine
	}
	return nil
}

func (x *ExprModel) GetPipe() *PipeExpr {
	if x != nil {
		return x.Pipe
	}
	return nil
}

func (x *ExprModel) GetCond() *CondExpr {
	if x != nil {
		return x.Cond
	}
	return nil
}

type CombineExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Args          []*ArgModel            `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineExpr) Reset() {
	*x = CombineExpr{}
	mi := &file_turnout_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineExpr) ProtoMessage() {}

func (x *CombineExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineExpr.ProtoReflect.Descriptor instead.
func (*CombineExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{10}
}

func (x *CombineExpr) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *CombineExpr) GetArgs() []*ArgModel {
	if x != nil {
		return x.Args
	}
	return nil
}

type PipeExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*PipeParam           `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Steps         []*PipeStep            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeExpr) Reset() {
	*x = PipeExpr{}
	mi := &file_turnout_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeExpr) ProtoMessage() {}

func (x *PipeExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeExpr.ProtoReflect.Descriptor instead.
func (*PipeExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{11}
}

func (x *PipeExpr) GetParams() []*PipeParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PipeExpr) GetSteps() []*PipeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type PipeParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamName     string                 `protobuf:"bytes,1,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	SourceIdent   string                 `protobuf:"bytes,2,opt,name=source_ident,json=sourceIdent,proto3" json:"source_ident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeParam) Reset() {
	*x = PipeParam{}
	mi := &file_turnout_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeParam) ProtoMessage() {}

func (x *PipeParam) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeParam.ProtoReflect.Descriptor instead.
func (*PipeParam) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{12}
}

func (x *PipeParam) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *PipeParam) GetSourceIdent() string {
	if x != nil {
		return x.SourceIdent
	}
	return ""
}

type PipeStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Args          []*ArgModel            `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeStep) Reset() {
	*x = PipeStep{}
	mi := &file_turnout_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeStep) ProtoMessage() {}

func (x *PipeStep) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeStep.ProtoReflect.Descriptor instead.
func (*PipeStep) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{13}
}

func (x *PipeStep) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *PipeStep) GetArgs() []*ArgModel {
	if x != nil {
		return x.Args
	}
	return nil
}

type CondExpr struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Condition *ArgModel              `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Then      *ArgModel              `protobuf:"bytes,2,opt,name=then,proto3" json:"then,omitempty"`
	// Note: field is named else_branch because "else" is a reserved word in
	// generated code. The JSON key is "elseBranch" (camelCase).
	ElseBranch    *ArgModel `protobuf:"bytes,3,opt,name=else_branch,json=elseBranch,proto3" json:"else_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondExpr) Reset() {
	*x = CondExpr{}
	mi := &file_turnout_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondExpr) ProtoMessage() {}

func (x *CondExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondExpr.ProtoReflect.Descriptor instead.
func (*CondExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{14}
}

func (x *CondExpr) GetCondition() *ArgModel {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *CondExpr) GetThen() *ArgModel {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *CondExpr) GetElseBranch() *ArgModel {
	if x != nil {
		return x.ElseBranch
	}
	return nil
}

type ArgModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of the following is present.
	Ref     *string         `protobuf:"bytes,1,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	Lit     *structpb.Value `protobuf:"bytes,2,opt,name=lit,proto3" json:"lit,omitempty"`
	FuncRef *string         `protobuf:"bytes,3,opt,name=func_ref,json=funcRef,proto3,oneof" json:"func_ref,omitempty"`
	// step_ref uses optional so that value 0 is serialised (not omitted).
	StepRef       *int32        `protobuf:"varint,4,opt,name=step_ref,json=stepRef,proto3,oneof" json:"step_ref,omitempty"`
	Transform     *TransformArg `protobuf:"bytes,5,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgModel) Reset() {
	*x = ArgModel{}
	mi := &file_turnout_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgModel) ProtoMessage() {}

func (x *ArgModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgModel.ProtoReflect.Descriptor instead.
func (*ArgModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{15}
}

func (x *ArgModel) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

func (x *ArgModel) GetLit() *structpb.Value {
	if x != nil {
		return x.Lit
	}
	return nil
}

func (x *ArgModel) GetFuncRef() string {
	if x != nil && x.FuncRef != nil {
		return *x.FuncRef
	}
	return ""
}

func (x *ArgModel) GetStepRef() int32 {
	if x != nil && x.StepRef != nil {
		return *x.StepRef
	}
	return 0
}

func (x *ArgModel) GetTransform() *TransformArg {
	if x != nil {
		return x.Transform
	}
	return nil
}

type TransformArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Fn            []string               `protobuf:"bytes,2,rep,name=fn,proto3" json:"fn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformArg) Reset() {
	*x = TransformArg{}
	mi := &file_turnout_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformArg) ProtoMessage() {}

func (x *TransformArg) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformArg.ProtoReflect.Descriptor instead.
func (*TransformArg) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{16}
}

func (x *TransformArg) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransformArg) GetFn() []string {
	if x != nil {
		return x.Fn
	}
	return nil
}

type PrepareEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Binding string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	// Exactly one of from_state or from_hook is present.
	FromState     *string `protobuf:"bytes,2,opt,name=from_state,json=fromState,proto3,oneof" json:"from_state,omitempty"`
	FromHook      *string `protobuf:"bytes,3,opt,name=from_hook,json=fromHook,proto3,oneof" json:"from_hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareEntry) Reset() {
	*x = PrepareEntry{}
	mi := &file_turnout_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareEntry) ProtoMessage() {}

func (x *PrepareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareEntry.ProtoReflect.Descriptor instead.
func (*PrepareEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{17}
}

func (x *PrepareEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *PrepareEntry) GetFromState() string {
	if x != nil && x.FromState != nil {
		return *x.FromState
	}
	return ""
}

func (x *PrepareEntry) GetFromHook() string {
	if x != nil && x.FromHook != nil {
		return *x.FromHook
	}
	return ""
}

type MergeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	ToState       string                 `protobuf:"bytes,2,opt,name=to_state,json=toState,proto3" json:"to_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeEntry) Reset() {
	*x = MergeEntry{}
	mi := &file_turnout_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeEntry) ProtoMessage() {}

func (x *MergeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeEntry.ProtoReflect.Descriptor instead.
func (*MergeEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{18}
}

func (x *MergeEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *MergeEntry) GetToState() string {
	if x != nil {
		return x.ToState
	}
	return ""
}

type NextRuleModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compute       *NextComputeModel      `protobuf:"bytes,1,opt,name=compute,proto3" json:"compute,omitempty"`
	Prepare       []*NextPrepareEntry    `protobuf:"bytes,2,rep,name=prepare,proto3" json:"prepare,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRuleModel) Reset() {
	*x = NextRuleModel{}
	mi := &file_turnout_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRuleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRuleModel) ProtoMessage() {}

func (x *NextRuleModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRuleModel.ProtoReflect.Descriptor instead.
func (*NextRuleModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{19}
}

func (x *NextRuleModel) GetCompute() *NextComputeModel {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *NextRuleModel) GetPrepare() []*NextPrepareEntry {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *NextRuleModel) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type NextComputeModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// condition is the binding name within prog whose boolean value gates the transition.
	Condition     string     `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Prog          *ProgModel `protobuf:"bytes,2,opt,name=prog,proto3" json:"prog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextComputeModel) Reset() {
	*x = NextComputeModel{}
	mi := &file_turnout_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextComputeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextComputeModel) ProtoMessage() {}

func (x *NextComputeModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextComputeModel.ProtoReflect.Descriptor instead.
func (*NextComputeModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{20}
}

func (x *NextComputeModel) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *NextComputeModel) GetProg() *ProgModel {
	if x != nil {
		return x.Prog
	}
	return nil
}

type NextPrepareEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Binding string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	// Exactly one of from_action, from_state, or from_literal is present.
	FromAction    *string         `protobuf:"bytes,2,opt,name=from_action,json=fromAction,proto3,oneof" json:"from_action,omitempty"`
	FromState     *string         `protobuf:"bytes,3,opt,name=from_state,json=fromState,proto3,oneof" json:"from_state,omitempty"`
	FromLiteral   *structpb.Value `protobuf:"bytes,4,opt,name=from_literal,json=fromLiteral,proto3" json:"from_literal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPrepareEntry) Reset() {
	*x = NextPrepareEntry{}
	mi := &file_turnout_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPrepareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPrepareEntry) ProtoMessage() {}

func (x *NextPrepareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPrepareEntry.ProtoReflect.Descriptor instead.
func (*NextPrepareEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{21}
}

func (x *NextPrepareEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *NextPrepareEntry) GetFromAction() string {
	if x != nil && x.FromAction != nil {
		return *x.FromAction
	}
	return ""
}

func (x *NextPrepareEntry) GetFromState() string {
	if x != nil && x.FromState != nil {
		return *x.FromState
	}
	return ""
}

func (x *NextPrepareEntry) GetFromLiteral() *structpb.Value {
	if x != nil {
		return x.FromLiteral
	}
	return nil
}

type RouteModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Match         []*MatchArm            `protobuf:"bytes,2,rep,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteModel) Reset() {
	*x = RouteModel{}
	mi := &file_turnout_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteModel) ProtoMessage() {}

func (x *RouteModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteModel.ProtoReflect.Descriptor instead.
func (*RouteModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{22}
}

func (x *RouteModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteModel) GetMatch() []*MatchArm {
	if x != nil {
		return x.Match
	}
	return nil
}

type MatchArm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// patterns holds raw pattern strings. "_" is fallback; "scene.action" or
	// "scene.*.action[.action...]" are path forms. Multiple entries are OR-joined.
	Patterns      []string `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Target        string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchArm) Reset() {
	*x = MatchArm{}
	mi := &file_turnout_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchArm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchArm) ProtoMessage() {}

func (x *MatchArm) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchArm.ProtoReflect.Descriptor instead.
func (*MatchArm) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{23}
}

func (x *MatchArm) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *MatchArm) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type LocalExprModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*LocalExprModel_Ref
	//	*LocalExprModel_Lit
	//	*LocalExprModel_It
	//	*LocalExprModel_Call
	//	*LocalExprModel_Infix
	//	*LocalExprModel_IfExpr
	//	*LocalExprModel_CaseExpr
	//	*LocalExprModel_PipeExpr
	Expr          isLocalExprModel_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalExprModel) Reset() {
	*x = LocalExprModel{}
	mi := &file_turnout_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExprModel) ProtoMessage() {}

func (x *LocalExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExprModel.ProtoReflect.Descriptor instead.
func (*LocalExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{24}
}

func (x *LocalExprModel) GetExpr() isLocalExprModel_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *LocalExprModel) GetRef() *LocalRefExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_Ref); ok {
			return x.Ref
		}
	}
	return nil
}

func (x *LocalExprModel) GetLit() *LocalLitExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_Lit); ok {
			return x.Lit
		}
	}
	return nil
}

func (x *LocalExprModel) GetIt() *LocalItExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_It); ok {
			return x.It
		}
	}
	return nil
}

func (x *LocalExprModel) GetCall() *LocalCallExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *LocalExprModel) GetInfix() *LocalInfixExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_Infix); ok {
			return x.Infix
		}
	}
	return nil
}

func (x *LocalExprModel) GetIfExpr() *LocalIfExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_IfExpr); ok {
			return x.IfExpr
		}
	}
	return nil
}

func (x *LocalExprModel) GetCaseExpr() *LocalCaseExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_CaseExpr); ok {
			return x.CaseExpr
		}
	}
	return nil
}

func (x *LocalExprModel) GetPipeExpr() *LocalPipeExprModel {
	if x != nil {
		if x, ok := x.Expr.(*LocalExprModel_PipeExpr); ok {
			return x.PipeExpr
		}
	}
	return nil
}

type isLocalExprModel_Expr interface {
	isLocalExprModel_Expr()
}

type LocalExprModel_Ref struct {
	Ref *LocalRefExprModel `protobuf:"bytes,1,opt,name=ref,proto3,oneof"`
}

type LocalExprModel_Lit struct {
	Lit *LocalLitExprModel `protobuf:"bytes,2,opt,name=lit,proto3,oneof"`
}

type LocalExprModel_It struct {
	It *LocalItExprModel `protobuf:"bytes,3,opt,name=it,proto3,oneof"`
}

type LocalExprModel_Call struct {
	Call *LocalCallExprModel `protobuf:"bytes,4,opt,name=call,proto3,oneof"`
}

type LocalExprModel_Infix struct {
	Infix *LocalInfixExprModel `protobuf:"bytes,5,opt,name=infix,proto3,oneof"`
}

type LocalExprModel_IfExpr struct {
	IfExpr *LocalIfExprModel `protobuf:"bytes,6,opt,name=if_expr,json=ifExpr,proto3,oneof"`
}

type LocalExprModel_CaseExpr struct {
	CaseExpr *LocalCaseExprModel `protobuf:"bytes,7,opt,name=case_expr,json=caseExpr,proto3,oneof"`
}

type LocalExprModel_PipeExpr struct {
	PipeExpr *LocalPipeExprModel `protobuf:"bytes,8,opt,name=pipe_expr,json=pipeExpr,proto3,oneof"`
}

func (*LocalExprModel_Ref) isLocalExprModel_Expr() {}

func (*LocalExprModel_Lit) isLocalExprModel_Expr() {}

func (*LocalExprModel_It) isLocalExprModel_Expr() {}

func (*LocalExprModel_Call) isLocalExprModel_Expr() {}

func (*LocalExprModel_Infix) isLocalExprModel_Expr() {}

func (*LocalExprModel_IfExpr) isLocalExprModel_Expr() {}

func (*LocalExprModel_CaseExpr) isLocalExprModel_Expr() {}

func (*LocalExprModel_PipeExpr) isLocalExprModel_Expr() {}

type LocalRefExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRefExprModel) Reset() {
	*x = LocalRefExprModel{}
	mi := &file_turnout_model_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRefExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRefExprModel) ProtoMessage() {}

func (x *LocalRefExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRefExprModel.ProtoReflect.Descriptor instead.
func (*LocalRefExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{25}
}

func (x *LocalRefExprModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LocalLitExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLitExprModel) Reset() {
	*x = LocalLitExprModel{}
	mi := &file_turnout_model_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLitExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLitExprModel) ProtoMessage() {}

func (x *LocalLitExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLitExprModel.ProtoReflect.Descriptor instead.
func (*LocalLitExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{26}
}

func (x *LocalLitExprModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LocalItExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalItExprModel) Reset() {
	*x = LocalItExprModel{}
	mi := &file_turnout_model_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalItExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalItExprModel) ProtoMessage() {}

func (x *LocalItExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalItExprModel.ProtoReflect.Descriptor instead.
func (*LocalItExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{27}
}

type LocalCallExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Args          []*LocalExprModel      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCallExprModel) Reset() {
	*x = LocalCallExprModel{}
	mi := &file_turnout_model_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCallExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCallExprModel) ProtoMessage() {}

func (x *LocalCallExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCallExprModel.ProtoReflect.Descriptor instead.
func (*LocalCallExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{28}
}

func (x *LocalCallExprModel) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *LocalCallExprModel) GetArgs() []*LocalExprModel {
	if x != nil {
		return x.Args
	}
	return nil
}

type LocalInfixExprModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// op is the ast.InfixOp iota value (0=&, 1=>=, 2=<=, 3=>, 4=<, 5=|, 6===,
	// 7=!=, 8=+, 9=-, 10=*, 11=/, 12=%). Value 8 (+) is type-dispatched at emit time.
	Op            int32           `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Lhs           *LocalExprModel `protobuf:"bytes,2,opt,name=lhs,proto3" json:"lhs,omitempty"`
	Rhs           *LocalExprModel `protobuf:"bytes,3,opt,name=rhs,proto3" json:"rhs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalInfixExprModel) Reset() {
	*x = LocalInfixExprModel{}
	mi := &file_turnout_model_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalInfixExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalInfixExprModel) ProtoMessage() {}

func (x *LocalInfixExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalInfixExprModel.ProtoReflect.Descriptor instead.
func (*LocalInfixExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{29}
}

func (x *LocalInfixExprModel) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *LocalInfixExprModel) GetLhs() *LocalExprModel {
	if x != nil {
		return x.Lhs
	}
	return nil
}

func (x *LocalInfixExprModel) GetRhs() *LocalExprModel {
	if x != nil {
		return x.Rhs
	}
	return nil
}

type LocalIfExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cond          *LocalExprModel        `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
	Then          *LocalExprModel        `protobuf:"bytes,2,opt,name=then,proto3" json:"then,omitempty"`
	ElseBranch    *LocalExprModel        `protobuf:"bytes,3,opt,name=else_branch,json=elseBranch,proto3" json:"else_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalIfExprModel) Reset() {
	*x = LocalIfExprModel{}
	mi := &file_turnout_model_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalIfExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalIfExprModel) ProtoMessage() {}

func (x *LocalIfExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalIfExprModel.ProtoReflect.Descriptor instead.
func (*LocalIfExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{30}
}

func (x *LocalIfExprModel) GetCond() *LocalExprModel {
	if x != nil {
		return x.Cond
	}
	return nil
}

func (x *LocalIfExprModel) GetThen() *LocalExprModel {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *LocalIfExprModel) GetElseBranch() *LocalExprModel {
	if x != nil {
		return x.ElseBranch
	}
	return nil
}

type LocalCaseArmModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *LocalCasePatternModel `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Guard         *LocalExprModel        `protobuf:"bytes,2,opt,name=guard,proto3" json:"guard,omitempty"` // nil when no guard
	Expr          *LocalExprModel        `protobuf:"bytes,3,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCaseArmModel) Reset() {
	*x = LocalCaseArmModel{}
	mi := &file_turnout_model_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCaseArmModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCaseArmModel) ProtoMessage() {}

func (x *LocalCaseArmModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCaseArmModel.ProtoReflect.Descriptor instead.
func (*LocalCaseArmModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{31}
}

func (x *LocalCaseArmModel) GetPattern() *LocalCasePatternModel {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *LocalCaseArmModel) GetGuard() *LocalExprModel {
	if x != nil {
		return x.Guard
	}
	return nil
}

func (x *LocalCaseArmModel) GetExpr() *LocalExprModel {
	if x != nil {
		return x.Expr
	}
	return nil
}

type LocalCaseExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *LocalExprModel        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Arms          []*LocalCaseArmModel   `protobuf:"bytes,2,rep,name=arms,proto3" json:"arms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCaseExprModel) Reset() {
	*x = LocalCaseExprModel{}
	mi := &file_turnout_model_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCaseExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCaseExprModel) ProtoMessage() {}

func (x *LocalCaseExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCaseExprModel.ProtoReflect.Descriptor instead.
func (*LocalCaseExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{32}
}

func (x *LocalCaseExprModel) GetSubject() *LocalExprModel {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *LocalCaseExprModel) GetArms() []*LocalCaseArmModel {
	if x != nil {
		return x.Arms
	}
	return nil
}

type LocalPipeExprModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initial       *LocalExprModel        `protobuf:"bytes,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Steps         []*LocalExprModel      `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalPipeExprModel) Reset() {
	*x = LocalPipeExprModel{}
	mi := &file_turnout_model_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalPipeExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPipeExprModel) ProtoMessage() {}

func (x *LocalPipeExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPipeExprModel.ProtoReflect.Descriptor instead.
func (*LocalPipeExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{33}
}

func (x *LocalPipeExprModel) GetInitial() *LocalExprModel {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *LocalPipeExprModel) GetSteps() []*LocalExprModel {
	if x != nil {
		return x.Steps
	}
	return nil
}

type LocalCasePatternModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Pattern:
	//
	//	*LocalCasePatternModel_Wildcard
	//	*LocalCasePatternModel_Lit
	//	*LocalCasePatternModel_VarBinder
	//	*LocalCasePatternModel_Tuple
	Pattern       isLocalCasePatternModel_Pattern `protobuf_oneof:"pattern"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCasePatternModel) Reset() {
	*x = LocalCasePatternModel{}
	mi := &file_turnout_model_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCasePatternModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCasePatternModel) ProtoMessage() {}

func (x *LocalCasePatternModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCasePatternModel.ProtoReflect.Descriptor instead.
func (*LocalCasePatternModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{34}
}

func (x *LocalCasePatternModel) GetPattern() isLocalCasePatternModel_Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *LocalCasePatternModel) GetWildcard() *LocalWildcardPatternModel {
	if x != nil {
		if x, ok := x.Pattern.(*LocalCasePatternModel_Wildcard); ok {
			return x.Wildcard
		}
	}
	return nil
}

func (x *LocalCasePatternModel) GetLit() *LocalLitPatternModel {
	if x != nil {
		if x, ok := x.Pattern.(*LocalCasePatternModel_Lit); ok {
			return x.Lit
		}
	}
	return nil
}

func (x *LocalCasePatternModel) GetVarBinder() *LocalVarBinderPatternModel {
	if x != nil {
		if x, ok := x.Pattern.(*LocalCasePatternModel_VarBinder); ok {
			return x.VarBinder
		}
	}
	return nil
}

func (x *LocalCasePatternModel) GetTuple() *LocalTuplePatternModel {
	if x != nil {
		if x, ok := x.Pattern.(*LocalCasePatternModel_Tuple); ok {
			return x.Tuple
		}
	}
	return nil
}

type isLocalCasePatternModel_Pattern interface {
	isLocalCasePatternModel_Pattern()
}

type LocalCasePatternModel_Wildcard struct {
	Wildcard *LocalWildcardPatternModel `protobuf:"bytes,1,opt,name=wildcard,proto3,oneof"`
}

type LocalCasePatternModel_Lit struct {
	Lit *LocalLitPatternModel `protobuf:"bytes,2,opt,name=lit,proto3,oneof"`
}

type LocalCasePatternModel_VarBinder struct {
	VarBinder *LocalVarBinderPatternModel `protobuf:"bytes,3,opt,name=var_binder,json=varBinder,proto3,oneof"`
}

type LocalCasePatternModel_Tuple struct {
	Tuple *LocalTuplePatternModel `protobuf:"bytes,4,opt,name=tuple,proto3,oneof"`
}

func (*LocalCasePatternModel_Wildcard) isLocalCasePatternModel_Pattern() {}

func (*LocalCasePatternModel_Lit) isLocalCasePatternModel_Pattern() {}

func (*LocalCasePatternModel_VarBinder) isLocalCasePatternModel_Pattern() {}

func (*LocalCasePatternModel_Tuple) isLocalCasePatternModel_Pattern() {}

type LocalWildcardPatternModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalWildcardPatternModel) Reset() {
	*x = LocalWildcardPatternModel{}
	mi := &file_turnout_model_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalWildcardPatternModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalWildcardPatternModel) ProtoMessage() {}

func (x *LocalWildcardPatternModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalWildcardPatternModel.ProtoReflect.Descriptor instead.
func (*LocalWildcardPatternModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{35}
}

type LocalLitPatternModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLitPatternModel) Reset() {
	*x = LocalLitPatternModel{}
	mi := &file_turnout_model_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLitPatternModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLitPatternModel) ProtoMessage() {}

func (x *LocalLitPatternModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLitPatternModel.ProtoReflect.Descriptor instead.
func (*LocalLitPatternModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{36}
}

func (x *LocalLitPatternModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LocalVarBinderPatternModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalVarBinderPatternModel) Reset() {
	*x = LocalVarBinderPatternModel{}
	mi := &file_turnout_model_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalVarBinderPatternModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalVarBinderPatternModel) ProtoMessage() {}

func (x *LocalVarBinderPatternModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalVarBinderPatternModel.ProtoReflect.Descriptor instead.
func (*LocalVarBinderPatternModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{37}
}

func (x *LocalVarBinderPatternModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LocalTuplePatternModel struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Elems         []*LocalCasePatternModel `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTuplePatternModel) Reset() {
	*x = LocalTuplePatternModel{}
	mi := &file_turnout_model_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTuplePatternModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTuplePatternModel) ProtoMessage() {}

func (x *LocalTuplePatternModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTuplePatternModel.ProtoReflect.Descriptor instead.
func (*LocalTuplePatternModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{38}
}

func (x *LocalTuplePatternModel) GetElems() []*LocalCasePatternModel {
	if x != nil {
		return x.Elems
	}
	return nil
}

var File_turnout_model_proto protoreflect.FileDescriptor

const file_turnout_model_proto_rawDesc = "" +
	"\n" +
	"\x13turnout-model.proto\x12\x10turnout.model.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xab\x01\n" +
	"\tTurnModel\x122\n" +
	"\x05state\x18\x01 \x01(\v2\x1c.turnout.model.v1.StateModelR\x05state\x124\n" +
	"\x06scenes\x18\x02 \x03(\v2\x1c.turnout.model.v1.SceneBlockR\x06scenes\x124\n" +
	"\x06routes\x18\x03 \x03(\v2\x1c.turnout.model.v1.RouteModelR\x06routes\"N\n" +
	"\n" +
	"StateModel\x12@\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2 .turnout.model.v1.NamespaceModelR\n" +
	"namespaces\"Z\n" +
	"\x0eNamespaceModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06fields\x18\x02 \x03(\v2\x1c.turnout.model.v1.FieldModelR\x06fields\"b\n" +
	"\n" +
	"FieldModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xb0\x01\n" +
	"\n" +
	"SceneBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rentry_actions\x18\x02 \x03(\tR\fentryActions\x12$\n" +
	"\vnext_policy\x18\x03 \x01(\tH\x00R\n" +
	"nextPolicy\x88\x01\x01\x127\n" +
	"\aactions\x18\x04 \x03(\v2\x1d.turnout.model.v1.ActionModelR\aactionsB\x0e\n" +
	"\f_next_policy\"\x94\x02\n" +
	"\vActionModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\acompute\x18\x02 \x01(\v2\x1e.turnout.model.v1.ComputeModelR\acompute\x128\n" +
	"\aprepare\x18\x03 \x03(\v2\x1e.turnout.model.v1.PrepareEntryR\aprepare\x122\n" +
	"\x05merge\x18\x04 \x03(\v2\x1c.turnout.model.v1.MergeEntryR\x05merge\x12\x18\n" +
	"\apublish\x18\x05 \x03(\tR\apublish\x123\n" +
	"\x04next\x18\x06 \x03(\v2\x1f.turnout.model.v1.NextRuleModelR\x04next\"S\n" +
	"\fComputeModel\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12/\n" +
	"\x04prog\x18\x02 \x01(\v2\x1b.turnout.model.v1.ProgModelR\x04prog\"[\n" +
	"\tProgModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\bbindings\x18\x02 \x03(\v2\x1e.turnout.model.v1.BindingModelR\bbindings\"\xd2\x01\n" +
	"\fBindingModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12/\n" +
	"\x04expr\x18\x04 \x01(\v2\x1b.turnout.model.v1.ExprModelR\x04expr\x12;\n" +
	"\bext_expr\x18\x05 \x01(\v2 .turnout.model.v1.LocalExprModelR\aextExpr\"\xa4\x01\n" +
	"\tExprModel\x127\n" +
	"\acombine\x18\x01 \x01(\v2\x1d.turnout.model.v1.CombineExprR\acombine\x12.\n" +
	"\x04pipe\x18\x02 \x01(\v2\x1a.turnout.model.v1.PipeExprR\x04pipe\x12.\n" +
	"\x04cond\x18\x03 \x01(\v2\x1a.turnout.model.v1.CondExprR\x04cond\"M\n" +
	"\vCombineExpr\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.turnout.model.v1.ArgModelR\x04args\"q\n" +
	"\bPipeExpr\x123\n" +
	"\x06params\x18\x01 \x03(\v2\x1b.turnout.model.v1.PipeParamR\x06params\x120\n" +
	"\x05steps\x18\x02 \x03(\v2\x1a.turnout.model.v1.PipeStepR\x05steps\"M\n" +
	"\tPipeParam\x12\x1d\n" +
	"\n" +
	"param_name\x18\x01 \x01(\tR\tparamName\x12!\n" +
	"\fsource_ident\x18\x02 \x01(\tR\vsourceIdent\"J\n" +
	"\bPipeStep\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.turnout.model.v1.ArgModelR\x04args\"\xb1\x01\n" +
	"\bCondExpr\x128\n" +
	"\tcondition\x18\x01 \x01(\v2\x1a.turnout.model.v1.ArgModelR\tcondition\x12.\n" +
	"\x04then\x18\x02 \x01(\v2\x1a.turnout.model.v1.ArgModelR\x04then\x12;\n" +
	"\velse_branch\x18\x03 \x01(\v2\x1a.turnout.model.v1.ArgModelR\n" +
	"elseBranch\"\xeb\x01\n" +
	"\bArgModel\x12\x15\n" +
	"\x03ref\x18\x01 \x01(\tH\x00R\x03ref\x88\x01\x01\x12(\n" +
	"\x03lit\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x03lit\x12\x1e\n" +
	"\bfunc_ref\x18\x03 \x01(\tH\x01R\afuncRef\x88\x01\x01\x12\x1e\n" +
	"\bstep_ref\x18\x04 \x01(\x05H\x02R\astepRef\x88\x01\x01\x12<\n" +
	"\ttransform\x18\x05 \x01(\v2\x1e.turnout.model.v1.TransformArgR\ttransformB\x06\n" +
	"\x04_refB\v\n" +
	"\t_func_refB\v\n" +
	"\t_step_ref\"0\n" +
	"\fTransformArg\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x0e\n" +
	"\x02fn\x18\x02 \x03(\tR\x02fn\"\x8b\x01\n" +
	"\fPrepareEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12\"\n" +
	"\n" +
	"from_state\x18\x02 \x01(\tH\x00R\tfromState\x88\x01\x01\x12 \n" +
	"\tfrom_hook\x18\x03 \x01(\tH\x01R\bfromHook\x88\x01\x01B\r\n" +
	"\v_from_stateB\f\n" +
	"\n" +
	"_from_hook\"A\n" +
	"\n" +
	"MergeEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12\x19\n" +
	"\bto_state\x18\x02 \x01(\tR\atoState\"\xa3\x01\n" +
	"\rNextRuleModel\x12<\n" +
	"\acompute\x18\x01 \x01(\v2\".turnout.model.v1.NextComputeModelR\acompute\x12<\n" +
	"\aprepare\x18\x02 \x03(\v2\".turnout.model.v1.NextPrepareEntryR\aprepare\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"a\n" +
	"\x10NextComputeModel\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12/\n" +
	"\x04prog\x18\x02 \x01(\v2\x1b.turnout.model.v1.ProgModelR\x04prog\"\xd0\x01\n" +
	"\x10NextPrepareEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12$\n" +
	"\vfrom_action\x18\x02 \x01(\tH\x00R\n" +
	"fromAction\x88\x01\x01\x12\"\n" +
	"\n" +
	"from_state\x18\x03 \x01(\tH\x01R\tfromState\x88\x01\x01\x129\n" +
	"\ffrom_literal\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\vfromLiteralB\x0e\n" +
	"\f_from_actionB\r\n" +
	"\v_from_state\"N\n" +
	"\n" +
	"RouteModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05match\x18\x02 \x03(\v2\x1a.turnout.model.v1.MatchArmR\x05match\">\n" +
	"\bMatchArm\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x84\x04\n" +
	"\x0eLocalExprModel\x127\n" +
	"\x03ref\x18\x01 \x01(\v2#.turnout.model.v1.LocalRefExprModelH\x00R\x03ref\x127\n" +
	"\x03lit\x18\x02 \x01(\v2#.turnout.model.v1.LocalLitExprModelH\x00R\x03lit\x124\n" +
	"\x02it\x18\x03 \x01(\v2\".turnout.model.v1.LocalItExprModelH\x00R\x02it\x12:\n" +
	"\x04call\x18\x04 \x01(\v2$.turnout.model.v1.LocalCallExprModelH\x00R\x04call\x12=\n" +
	"\x05infix\x18\x05 \x01(\v2%.turnout.model.v1.LocalInfixExprModelH\x00R\x05infix\x12=\n" +
	"\aif_expr\x18\x06 \x01(\v2\".turnout.model.v1.LocalIfExprModelH\x00R\x06ifExpr\x12C\n" +
	"\tcase_expr\x18\a \x01(\v2$.turnout.model.v1.LocalCaseExprModelH\x00R\bcaseExpr\x12C\n" +
	"\tpipe_expr\x18\b \x01(\v2$.turnout.model.v1.LocalPipeExprModelH\x00R\bpipeExprB\x06\n" +
	"\x04expr\"'\n" +
	"\x11LocalRefExprModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x11LocalLitExprModel\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\x12\n" +
	"\x10LocalItExprModel\"Z\n" +
	"\x12LocalCallExprModel\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x124\n" +
	"\x04args\x18\x02 \x03(\v2 .turnout.model.v1.LocalExprModelR\x04args\"\x8d\x01\n" +
	"\x13LocalInfixExprModel\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x122\n" +
	"\x03lhs\x18\x02 \x01(\v2 .turnout.model.v1.LocalExprModelR\x03lhs\x122\n" +
	"\x03rhs\x18\x03 \x01(\v2 .turnout.model.v1.LocalExprModelR\x03rhs\"\xc1\x01\n" +
	"\x10LocalIfExprModel\x124\n" +
	"\x04cond\x18\x01 \x01(\v2 .turnout.model.v1.LocalExprModelR\x04cond\x124\n" +
	"\x04then\x18\x02 \x01(\v2 .turnout.model.v1.LocalExprModelR\x04then\x12A\n" +
	"\velse_branch\x18\x03 \x01(\v2 .turnout.model.v1.LocalExprModelR\n" +
	"elseBranch\"\xc4\x01\n" +
	"\x11LocalCaseArmModel\x12A\n" +
	"\apattern\x18\x01 \x01(\v2'.turnout.model.v1.LocalCasePatternModelR\apattern\x126\n" +
	"\x05guard\x18\x02 \x01(\v2 .turnout.model.v1.LocalExprModelR\x05guard\x124\n" +
	"\x04expr\x18\x03 \x01(\v2 .turnout.model.v1.LocalExprModelR\x04expr\"\x89\x01\n" +
	"\x12LocalCaseExprModel\x12:\n" +
	"\asubject\x18\x01 \x01(\v2 .turnout.model.v1.LocalExprModelR\asubject\x127\n" +
	"\x04arms\x18\x02 \x03(\v2#.turnout.model.v1.LocalCaseArmModelR\x04arms\"\x88\x01\n" +
	"\x12LocalPipeExprModel\x12:\n" +
	"\ainitial\x18\x01 \x01(\v2 .turnout.model.v1.LocalExprModelR\ainitial\x126\n" +
	"\x05steps\x18\x02 \x03(\v2 .turnout.model.v1.LocalExprModelR\x05steps\"\xba\x02\n" +
	"\x15LocalCasePatternModel\x12I\n" +
	"\bwildcard\x18\x01 \x01(\v2+.turnout.model.v1.LocalWildcardPatternModelH\x00R\bwildcard\x12:\n" +
	"\x03lit\x18\x02 \x01(\v2&.turnout.model.v1.LocalLitPatternModelH\x00R\x03lit\x12M\n" +
	"\n" +
	"var_binder\x18\x03 \x01(\v2,.turnout.model.v1.LocalVarBinderPatternModelH\x00R\tvarBinder\x12@\n" +
	"\x05tuple\x18\x04 \x01(\v2(.turnout.model.v1.LocalTuplePatternModelH\x00R\x05tupleB\t\n" +
	"\apattern\"\x1b\n" +
	"\x19LocalWildcardPatternModel\"D\n" +
	"\x14LocalLitPatternModel\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\"0\n" +
	"\x1aLocalVarBinderPatternModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"W\n" +
	"\x16LocalTuplePatternModel\x12=\n" +
	"\x05elems\x18\x01 \x03(\v2'.turnout.model.v1.LocalCasePatternModelR\x05elemsBIZGgithub.com/kozmof/turnout/packages/go/converter/internal/emit/turnoutpbb\x06proto3"

var (
	file_turnout_model_proto_rawDescOnce sync.Once
	file_turnout_model_proto_rawDescData []byte
)

func file_turnout_model_proto_rawDescGZIP() []byte {
	file_turnout_model_proto_rawDescOnce.Do(func() {
		file_turnout_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turnout_model_proto_rawDesc), len(file_turnout_model_proto_rawDesc)))
	})
	return file_turnout_model_proto_rawDescData
}

var file_turnout_model_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_turnout_model_proto_goTypes = []any{
	(*TurnModel)(nil),                  // 0: turnout.model.v1.TurnModel
	(*StateModel)(nil),                 // 1: turnout.model.v1.StateModel
	(*NamespaceModel)(nil),             // 2: turnout.model.v1.NamespaceModel
	(*FieldModel)(nil),                 // 3: turnout.model.v1.FieldModel
	(*SceneBlock)(nil),                 // 4: turnout.model.v1.SceneBlock
	(*ActionModel)(nil),                // 5: turnout.model.v1.ActionModel
	(*ComputeModel)(nil),               // 6: turnout.model.v1.ComputeModel
	(*ProgModel)(nil),                  // 7: turnout.model.v1.ProgModel
	(*BindingModel)(nil),               // 8: turnout.model.v1.BindingModel
	(*ExprModel)(nil),                  // 9: turnout.model.v1.ExprModel
	(*CombineExpr)(nil),                // 10: turnout.model.v1.CombineExpr
	(*PipeExpr)(nil),                   // 11: turnout.model.v1.PipeExpr
	(*PipeParam)(nil),                  // 12: turnout.model.v1.PipeParam
	(*PipeStep)(nil),                   // 13: turnout.model.v1.PipeStep
	(*CondExpr)(nil),                   // 14: turnout.model.v1.CondExpr
	(*ArgModel)(nil),                   // 15: turnout.model.v1.ArgModel
	(*TransformArg)(nil),               // 16: turnout.model.v1.TransformArg
	(*PrepareEntry)(nil),               // 17: turnout.model.v1.PrepareEntry
	(*MergeEntry)(nil),                 // 18: turnout.model.v1.MergeEntry
	(*NextRuleModel)(nil),              // 19: turnout.model.v1.NextRuleModel
	(*NextComputeModel)(nil),           // 20: turnout.model.v1.NextComputeModel
	(*NextPrepareEntry)(nil),           // 21: turnout.model.v1.NextPrepareEntry
	(*RouteModel)(nil),                 // 22: turnout.model.v1.RouteModel
	(*MatchArm)(nil),                   // 23: turnout.model.v1.MatchArm
	(*LocalExprModel)(nil),             // 24: turnout.model.v1.LocalExprModel
	(*LocalRefExprModel)(nil),          // 25: turnout.model.v1.LocalRefExprModel
	(*LocalLitExprModel)(nil),          // 26: turnout.model.v1.LocalLitExprModel
	(*LocalItExprModel)(nil),           // 27: turnout.model.v1.LocalItExprModel
	(*LocalCallExprModel)(nil),         // 28: turnout.model.v1.LocalCallExprModel
	(*LocalInfixExprModel)(nil),        // 29: turnout.model.v1.LocalInfixExprModel
	(*LocalIfExprModel)(nil),           // 30: turnout.model.v1.LocalIfExprModel
	(*LocalCaseArmModel)(nil),          // 31: turnout.model.v1.LocalCaseArmModel
	(*LocalCaseExprModel)(nil),         // 32: turnout.model.v1.LocalCaseExprModel
	(*LocalPipeExprModel)(nil),         // 33: turnout.model.v1.LocalPipeExprModel
	(*LocalCasePatternModel)(nil),      // 34: turnout.model.v1.LocalCasePatternModel
	(*LocalWildcardPatternModel)(nil),  // 35: turnout.model.v1.LocalWildcardPatternModel
	(*LocalLitPatternModel)(nil),       // 36: turnout.model.v1.LocalLitPatternModel
	(*LocalVarBinderPatternModel)(nil), // 37: turnout.model.v1.LocalVarBinderPatternModel
	(*LocalTuplePatternModel)(nil),     // 38: turnout.model.v1.LocalTuplePatternModel
	(*structpb.Value)(nil),             // 39: google.protobuf.Value
}
var file_turnout_model_proto_depIdxs = []int32{
	1,  // 0: turnout.model.v1.TurnModel.state:type_name -> turnout.model.v1.StateModel
	4,  // 1: turnout.model.v1.TurnModel.scenes:type_name -> turnout.model.v1.SceneBlock
	22, // 2: turnout.model.v1.TurnModel.routes:type_name -> turnout.model.v1.RouteModel
	2,  // 3: turnout.model.v1.StateModel.namespaces:type_name -> turnout.model.v1.NamespaceModel
	3,  // 4: turnout.model.v1.NamespaceModel.fields:type_name -> turnout.model.v1.FieldModel
	39, // 5: turnout.model.v1.FieldModel.value:type_name -> google.protobuf.Value
	5,  // 6: turnout.model.v1.SceneBlock.actions:type_name -> turnout.model.v1.ActionModel
	6,  // 7: turnout.model.v1.ActionModel.compute:type_name -> turnout.model.v1.ComputeModel
	17, // 8: turnout.model.v1.ActionModel.prepare:type_name -> turnout.model.v1.PrepareEntry
	18, // 9: turnout.model.v1.ActionModel.merge:type_name -> turnout.model.v1.MergeEntry
	19, // 10: turnout.model.v1.ActionModel.next:type_name -> turnout.model.v1.NextRuleModel
	7,  // 11: turnout.model.v1.ComputeModel.prog:type_name -> turnout.model.v1.ProgModel
	8,  // 12: turnout.model.v1.ProgModel.bindings:type_name -> turnout.model.v1.BindingModel
	39, // 13: turnout.model.v1.BindingModel.value:type_name -> google.protobuf.Value
	9,  // 14: turnout.model.v1.BindingModel.expr:type_name -> turnout.model.v1.ExprModel
	24, // 15: turnout.model.v1.BindingModel.ext_expr:type_name -> turnout.model.v1.LocalExprModel
	10, // 16: turnout.model.v1.ExprModel.combine:type_name -> turnout.model.v1.CombineExpr
	11, // 17: turnout.model.v1.ExprModel.pipe:type_name -> turnout.model.v1.PipeExpr
	14, // 18: turnout.model.v1.ExprModel.cond:type_name -> turnout.model.v1.CondExpr
	15, // 19: turnout.model.v1.CombineExpr.args:type_name -> turnout.model.v1.ArgModel
	12, // 20: turnout.model.v1.PipeExpr.params:type_name -> turnout.model.v1.PipeParam
	13, // 21: turnout.model.v1.PipeExpr.steps:type_name -> turnout.model.v1.PipeStep
	15, // 22: turnout.model.v1.PipeStep.args:type_name -> turnout.model.v1.ArgModel
	15, // 23: turnout.model.v1.CondExpr.condition:type_name -> turnout.model.v1.ArgModel
	15, // 24: turnout.model.v1.CondExpr.then:type_name -> turnout.model.v1.ArgModel
	15, // 25: turnout.model.v1.CondExpr.else_branch:type_name -> turnout.model.v1.ArgModel
	39, // 26: turnout.model.v1.ArgModel.lit:type_name -> google.protobuf.Value
	16, // 27: turnout.model.v1.ArgModel.transform:type_name -> turnout.model.v1.TransformArg
	20, // 28: turnout.model.v1.NextRuleModel.compute:type_name -> turnout.model.v1.NextComputeModel
	21, // 29: turnout.model.v1.NextRuleModel.prepare:type_name -> turnout.model.v1.NextPrepareEntry
	7,  // 30: turnout.model.v1.NextComputeModel.prog:type_name -> turnout.model.v1.ProgModel
	39, // 31: turnout.model.v1.NextPrepareEntry.from_literal:type_name -> google.protobuf.Value
	23, // 32: turnout.model.v1.RouteModel.match:type_name -> turnout.model.v1.MatchArm
	25, // 33: turnout.model.v1.LocalExprModel.ref:type_name -> turnout.model.v1.LocalRefExprModel
	26, // 34: turnout.model.v1.LocalExprModel.lit:type_name -> turnout.model.v1.LocalLitExprModel
	27, // 35: turnout.model.v1.LocalExprModel.it:type_name -> turnout.model.v1.LocalItExprModel
	28, // 36: turnout.model.v1.LocalExprModel.call:type_name -> turnout.model.v1.LocalCallExprModel
	29, // 37: turnout.model.v1.LocalExprModel.infix:type_name -> turnout.model.v1.LocalInfixExprModel
	30, // 38: turnout.model.v1.LocalExprModel.if_expr:type_name -> turnout.model.v1.LocalIfExprModel
	32, // 39: turnout.model.v1.LocalExprModel.case_expr:type_name -> turnout.model.v1.LocalCaseExprModel
	33, // 40: turnout.model.v1.LocalExprModel.pipe_expr:type_name -> turnout.model.v1.LocalPipeExprModel
	39, // 41: turnout.model.v1.LocalLitExprModel.value:type_name -> google.protobuf.Value
	24, // 42: turnout.model.v1.LocalCallExprModel.args:type_name -> turnout.model.v1.LocalExprModel
	24, // 43: turnout.model.v1.LocalInfixExprModel.lhs:type_name -> turnout.model.v1.LocalExprModel
	24, // 44: turnout.model.v1.LocalInfixExprModel.rhs:type_name -> turnout.model.v1.LocalExprModel
	24, // 45: turnout.model.v1.LocalIfExprModel.cond:type_name -> turnout.model.v1.LocalExprModel
	24, // 46: turnout.model.v1.LocalIfExprModel.then:type_name -> turnout.model.v1.LocalExprModel
	24, // 47: turnout.model.v1.LocalIfExprModel.else_branch:type_name -> turnout.model.v1.LocalExprModel
	34, // 48: turnout.model.v1.LocalCaseArmModel.pattern:type_name -> turnout.model.v1.LocalCasePatternModel
	24, // 49: turnout.model.v1.LocalCaseArmModel.guard:type_name -> turnout.model.v1.LocalExprModel
	24, // 50: turnout.model.v1.LocalCaseArmModel.expr:type_name -> turnout.model.v1.LocalExprModel
	24, // 51: turnout.model.v1.LocalCaseExprModel.subject:type_name -> turnout.model.v1.LocalExprModel
	31, // 52: turnout.model.v1.LocalCaseExprModel.arms:type_name -> turnout.model.v1.LocalCaseArmModel
	24, // 53: turnout.model.v1.LocalPipeExprModel.initial:type_name -> turnout.model.v1.LocalExprModel
	24, // 54: turnout.model.v1.LocalPipeExprModel.steps:type_name -> turnout.model.v1.LocalExprModel
	35, // 55: turnout.model.v1.LocalCasePatternModel.wildcard:type_name -> turnout.model.v1.LocalWildcardPatternModel
	36, // 56: turnout.model.v1.LocalCasePatternModel.lit:type_name -> turnout.model.v1.LocalLitPatternModel
	37, // 57: turnout.model.v1.LocalCasePatternModel.var_binder:type_name -> turnout.model.v1.LocalVarBinderPatternModel
	38, // 58: turnout.model.v1.LocalCasePatternModel.tuple:type_name -> turnout.model.v1.LocalTuplePatternModel
	39, // 59: turnout.model.v1.LocalLitPatternModel.value:type_name -> google.protobuf.Value
	34, // 60: turnout.model.v1.LocalTuplePatternModel.elems:type_name -> turnout.model.v1.LocalCasePatternModel
	61, // [61:61] is the sub-list for method output_type
	61, // [61:61] is the sub-list for method input_type
	61, // [61:61] is the sub-list for extension type_name
	61, // [61:61] is the sub-list for extension extendee
	0,  // [0:61] is the sub-list for field type_name
}

func init() { file_turnout_model_proto_init() }
func file_turnout_model_proto_init() {
	if File_turnout_model_proto != nil {
		return
	}
	file_turnout_model_proto_msgTypes[4].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[15].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[17].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[21].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[24].OneofWrappers = []any{
		(*LocalExprModel_Ref)(nil),
		(*LocalExprModel_Lit)(nil),
		(*LocalExprModel_It)(nil),
		(*LocalExprModel_Call)(nil),
		(*LocalExprModel_Infix)(nil),
		(*LocalExprModel_IfExpr)(nil),
		(*LocalExprModel_CaseExpr)(nil),
		(*LocalExprModel_PipeExpr)(nil),
	}
	file_turnout_model_proto_msgTypes[34].OneofWrappers = []any{
		(*LocalCasePatternModel_Wildcard)(nil),
		(*LocalCasePatternModel_Lit)(nil),
		(*LocalCasePatternModel_VarBinder)(nil),
		(*LocalCasePatternModel_Tuple)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turnout_model_proto_rawDesc), len(file_turnout_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turnout_model_proto_goTypes,
		DependencyIndexes: file_turnout_model_proto_depIdxs,
		MessageInfos:      file_turnout_model_proto_msgTypes,
	}.Build()
	File_turnout_model_proto = out.File
	file_turnout_model_proto_goTypes = nil
	file_turnout_model_proto_depIdxs = nil
}
