// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: turnout-model.proto

// Package turnout.model.v1 is the single source of truth for the JSON contract
// emitted by the Go converter (-format json) and consumed by the TypeScript
// scene-runner. Changing this file and running `buf generate` from the repo
// root regenerates both the Go and TypeScript types automatically.

package turnoutpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TurnModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *StateModel            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Scenes        []*SceneBlock          `protobuf:"bytes,2,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Routes        []*RouteModel          `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnModel) Reset() {
	*x = TurnModel{}
	mi := &file_turnout_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnModel) ProtoMessage() {}

func (x *TurnModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnModel.ProtoReflect.Descriptor instead.
func (*TurnModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{0}
}

func (x *TurnModel) GetState() *StateModel {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TurnModel) GetScenes() []*SceneBlock {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *TurnModel) GetRoutes() []*RouteModel {
	if x != nil {
		return x.Routes
	}
	return nil
}

type StateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*NamespaceModel      `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateModel) Reset() {
	*x = StateModel{}
	mi := &file_turnout_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateModel) ProtoMessage() {}

func (x *StateModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateModel.ProtoReflect.Descriptor instead.
func (*StateModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{1}
}

func (x *StateModel) GetNamespaces() []*NamespaceModel {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type NamespaceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*FieldModel          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceModel) Reset() {
	*x = NamespaceModel{}
	mi := &file_turnout_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceModel) ProtoMessage() {}

func (x *NamespaceModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceModel.ProtoReflect.Descriptor instead.
func (*NamespaceModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceModel) GetFields() []*FieldModel {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FieldModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is one of: "number" | "str" | "bool" | "arr<number>" | "arr<str>" | "arr<bool>"
	Type          string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldModel) Reset() {
	*x = FieldModel{}
	mi := &file_turnout_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldModel) ProtoMessage() {}

func (x *FieldModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldModel.ProtoReflect.Descriptor instead.
func (*FieldModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{3}
}

func (x *FieldModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SceneBlock struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntryActions []string               `protobuf:"bytes,2,rep,name=entry_actions,json=entryActions,proto3" json:"entry_actions,omitempty"`
	// next_policy is one of: "first-match" | "all-match". Absent means first-match.
	NextPolicy    *string        `protobuf:"bytes,3,opt,name=next_policy,json=nextPolicy,proto3,oneof" json:"next_policy,omitempty"`
	Actions       []*ActionModel `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneBlock) Reset() {
	*x = SceneBlock{}
	mi := &file_turnout_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneBlock) ProtoMessage() {}

func (x *SceneBlock) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneBlock.ProtoReflect.Descriptor instead.
func (*SceneBlock) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{4}
}

func (x *SceneBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SceneBlock) GetEntryActions() []string {
	if x != nil {
		return x.EntryActions
	}
	return nil
}

func (x *SceneBlock) GetNextPolicy() string {
	if x != nil && x.NextPolicy != nil {
		return *x.NextPolicy
	}
	return ""
}

func (x *SceneBlock) GetActions() []*ActionModel {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ActionModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compute       *ComputeModel          `protobuf:"bytes,2,opt,name=compute,proto3" json:"compute,omitempty"`
	Prepare       []*PrepareEntry        `protobuf:"bytes,3,rep,name=prepare,proto3" json:"prepare,omitempty"`
	Merge         []*MergeEntry          `protobuf:"bytes,4,rep,name=merge,proto3" json:"merge,omitempty"`
	Publish       []string               `protobuf:"bytes,5,rep,name=publish,proto3" json:"publish,omitempty"`
	Next          []*NextRuleModel       `protobuf:"bytes,6,rep,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionModel) Reset() {
	*x = ActionModel{}
	mi := &file_turnout_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionModel) ProtoMessage() {}

func (x *ActionModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionModel.ProtoReflect.Descriptor instead.
func (*ActionModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{5}
}

func (x *ActionModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionModel) GetCompute() *ComputeModel {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *ActionModel) GetPrepare() []*PrepareEntry {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *ActionModel) GetMerge() []*MergeEntry {
	if x != nil {
		return x.Merge
	}
	return nil
}

func (x *ActionModel) GetPublish() []string {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *ActionModel) GetNext() []*NextRuleModel {
	if x != nil {
		return x.Next
	}
	return nil
}

type ComputeModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// root is the binding name whose resolved value is the action's compute output.
	Root          string     `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Prog          *ProgModel `protobuf:"bytes,2,opt,name=prog,proto3" json:"prog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeModel) Reset() {
	*x = ComputeModel{}
	mi := &file_turnout_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeModel) ProtoMessage() {}

func (x *ComputeModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeModel.ProtoReflect.Descriptor instead.
func (*ComputeModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{6}
}

func (x *ComputeModel) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ComputeModel) GetProg() *ProgModel {
	if x != nil {
		return x.Prog
	}
	return nil
}

type ProgModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bindings      []*BindingModel        `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgModel) Reset() {
	*x = ProgModel{}
	mi := &file_turnout_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgModel) ProtoMessage() {}

func (x *ProgModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgModel.ProtoReflect.Descriptor instead.
func (*ProgModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{7}
}

func (x *ProgModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgModel) GetBindings() []*BindingModel {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type BindingModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is a FieldTypeStr: "number" | "str" | "bool" | "arr<number>" | "arr<str>" | "arr<bool>"
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Exactly one of value or expr is present.
	Value         *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expr          *ExprModel      `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingModel) Reset() {
	*x = BindingModel{}
	mi := &file_turnout_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingModel) ProtoMessage() {}

func (x *BindingModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingModel.ProtoReflect.Descriptor instead.
func (*BindingModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{8}
}

func (x *BindingModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BindingModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BindingModel) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BindingModel) GetExpr() *ExprModel {
	if x != nil {
		return x.Expr
	}
	return nil
}

type ExprModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of combine, pipe, or cond is present.
	Combine       *CombineExpr `protobuf:"bytes,1,opt,name=combine,proto3" json:"combine,omitempty"`
	Pipe          *PipeExpr    `protobuf:"bytes,2,opt,name=pipe,proto3" json:"pipe,omitempty"`
	Cond          *CondExpr    `protobuf:"bytes,3,opt,name=cond,proto3" json:"cond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExprModel) Reset() {
	*x = ExprModel{}
	mi := &file_turnout_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprModel) ProtoMessage() {}

func (x *ExprModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExprModel.ProtoReflect.Descriptor instead.
func (*ExprModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{9}
}

func (x *ExprModel) GetCombine() *CombineExpr {
	if x != nil {
		return x.Combine
	}
	return nil
}

func (x *ExprModel) GetPipe() *PipeExpr {
	if x != nil {
		return x.Pipe
	}
	return nil
}

func (x *ExprModel) GetCond() *CondExpr {
	if x != nil {
		return x.Cond
	}
	return nil
}

type CombineExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Args          []*ArgModel            `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineExpr) Reset() {
	*x = CombineExpr{}
	mi := &file_turnout_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineExpr) ProtoMessage() {}

func (x *CombineExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineExpr.ProtoReflect.Descriptor instead.
func (*CombineExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{10}
}

func (x *CombineExpr) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *CombineExpr) GetArgs() []*ArgModel {
	if x != nil {
		return x.Args
	}
	return nil
}

type PipeExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*PipeParam           `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Steps         []*PipeStep            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeExpr) Reset() {
	*x = PipeExpr{}
	mi := &file_turnout_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeExpr) ProtoMessage() {}

func (x *PipeExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeExpr.ProtoReflect.Descriptor instead.
func (*PipeExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{11}
}

func (x *PipeExpr) GetParams() []*PipeParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PipeExpr) GetSteps() []*PipeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type PipeParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamName     string                 `protobuf:"bytes,1,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	SourceIdent   string                 `protobuf:"bytes,2,opt,name=source_ident,json=sourceIdent,proto3" json:"source_ident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeParam) Reset() {
	*x = PipeParam{}
	mi := &file_turnout_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeParam) ProtoMessage() {}

func (x *PipeParam) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeParam.ProtoReflect.Descriptor instead.
func (*PipeParam) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{12}
}

func (x *PipeParam) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *PipeParam) GetSourceIdent() string {
	if x != nil {
		return x.SourceIdent
	}
	return ""
}

type PipeStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Args          []*ArgModel            `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeStep) Reset() {
	*x = PipeStep{}
	mi := &file_turnout_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeStep) ProtoMessage() {}

func (x *PipeStep) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeStep.ProtoReflect.Descriptor instead.
func (*PipeStep) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{13}
}

func (x *PipeStep) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *PipeStep) GetArgs() []*ArgModel {
	if x != nil {
		return x.Args
	}
	return nil
}

type CondExpr struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Condition *ArgModel              `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Then      *ArgModel              `protobuf:"bytes,2,opt,name=then,proto3" json:"then,omitempty"`
	// Note: field is named else_branch because "else" is a reserved word in
	// generated code. The JSON key is "elseBranch" (camelCase).
	ElseBranch    *ArgModel `protobuf:"bytes,3,opt,name=else_branch,json=elseBranch,proto3" json:"else_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondExpr) Reset() {
	*x = CondExpr{}
	mi := &file_turnout_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondExpr) ProtoMessage() {}

func (x *CondExpr) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondExpr.ProtoReflect.Descriptor instead.
func (*CondExpr) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{14}
}

func (x *CondExpr) GetCondition() *ArgModel {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *CondExpr) GetThen() *ArgModel {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *CondExpr) GetElseBranch() *ArgModel {
	if x != nil {
		return x.ElseBranch
	}
	return nil
}

type ArgModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of the following is present.
	Ref     *string         `protobuf:"bytes,1,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	Lit     *structpb.Value `protobuf:"bytes,2,opt,name=lit,proto3" json:"lit,omitempty"`
	FuncRef *string         `protobuf:"bytes,3,opt,name=func_ref,json=funcRef,proto3,oneof" json:"func_ref,omitempty"`
	// step_ref uses optional so that value 0 is serialised (not omitted).
	StepRef       *int32        `protobuf:"varint,4,opt,name=step_ref,json=stepRef,proto3,oneof" json:"step_ref,omitempty"`
	Transform     *TransformArg `protobuf:"bytes,5,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgModel) Reset() {
	*x = ArgModel{}
	mi := &file_turnout_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgModel) ProtoMessage() {}

func (x *ArgModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgModel.ProtoReflect.Descriptor instead.
func (*ArgModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{15}
}

func (x *ArgModel) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

func (x *ArgModel) GetLit() *structpb.Value {
	if x != nil {
		return x.Lit
	}
	return nil
}

func (x *ArgModel) GetFuncRef() string {
	if x != nil && x.FuncRef != nil {
		return *x.FuncRef
	}
	return ""
}

func (x *ArgModel) GetStepRef() int32 {
	if x != nil && x.StepRef != nil {
		return *x.StepRef
	}
	return 0
}

func (x *ArgModel) GetTransform() *TransformArg {
	if x != nil {
		return x.Transform
	}
	return nil
}

type TransformArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Fn            string                 `protobuf:"bytes,2,opt,name=fn,proto3" json:"fn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformArg) Reset() {
	*x = TransformArg{}
	mi := &file_turnout_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformArg) ProtoMessage() {}

func (x *TransformArg) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformArg.ProtoReflect.Descriptor instead.
func (*TransformArg) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{16}
}

func (x *TransformArg) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransformArg) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

type PrepareEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Binding string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	// Exactly one of from_state or from_hook is present.
	FromState     *string `protobuf:"bytes,2,opt,name=from_state,json=fromState,proto3,oneof" json:"from_state,omitempty"`
	FromHook      *string `protobuf:"bytes,3,opt,name=from_hook,json=fromHook,proto3,oneof" json:"from_hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareEntry) Reset() {
	*x = PrepareEntry{}
	mi := &file_turnout_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareEntry) ProtoMessage() {}

func (x *PrepareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareEntry.ProtoReflect.Descriptor instead.
func (*PrepareEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{17}
}

func (x *PrepareEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *PrepareEntry) GetFromState() string {
	if x != nil && x.FromState != nil {
		return *x.FromState
	}
	return ""
}

func (x *PrepareEntry) GetFromHook() string {
	if x != nil && x.FromHook != nil {
		return *x.FromHook
	}
	return ""
}

type MergeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	ToState       string                 `protobuf:"bytes,2,opt,name=to_state,json=toState,proto3" json:"to_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeEntry) Reset() {
	*x = MergeEntry{}
	mi := &file_turnout_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeEntry) ProtoMessage() {}

func (x *MergeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeEntry.ProtoReflect.Descriptor instead.
func (*MergeEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{18}
}

func (x *MergeEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *MergeEntry) GetToState() string {
	if x != nil {
		return x.ToState
	}
	return ""
}

type NextRuleModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compute       *NextComputeModel      `protobuf:"bytes,1,opt,name=compute,proto3" json:"compute,omitempty"`
	Prepare       []*NextPrepareEntry    `protobuf:"bytes,2,rep,name=prepare,proto3" json:"prepare,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRuleModel) Reset() {
	*x = NextRuleModel{}
	mi := &file_turnout_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRuleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRuleModel) ProtoMessage() {}

func (x *NextRuleModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRuleModel.ProtoReflect.Descriptor instead.
func (*NextRuleModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{19}
}

func (x *NextRuleModel) GetCompute() *NextComputeModel {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *NextRuleModel) GetPrepare() []*NextPrepareEntry {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *NextRuleModel) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type NextComputeModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// condition is the binding name within prog whose boolean value gates the transition.
	Condition     string     `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Prog          *ProgModel `protobuf:"bytes,2,opt,name=prog,proto3" json:"prog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextComputeModel) Reset() {
	*x = NextComputeModel{}
	mi := &file_turnout_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextComputeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextComputeModel) ProtoMessage() {}

func (x *NextComputeModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextComputeModel.ProtoReflect.Descriptor instead.
func (*NextComputeModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{20}
}

func (x *NextComputeModel) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *NextComputeModel) GetProg() *ProgModel {
	if x != nil {
		return x.Prog
	}
	return nil
}

type NextPrepareEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Binding string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	// Exactly one of from_action, from_state, or from_literal is present.
	FromAction    *string         `protobuf:"bytes,2,opt,name=from_action,json=fromAction,proto3,oneof" json:"from_action,omitempty"`
	FromState     *string         `protobuf:"bytes,3,opt,name=from_state,json=fromState,proto3,oneof" json:"from_state,omitempty"`
	FromLiteral   *structpb.Value `protobuf:"bytes,4,opt,name=from_literal,json=fromLiteral,proto3" json:"from_literal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPrepareEntry) Reset() {
	*x = NextPrepareEntry{}
	mi := &file_turnout_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPrepareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPrepareEntry) ProtoMessage() {}

func (x *NextPrepareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPrepareEntry.ProtoReflect.Descriptor instead.
func (*NextPrepareEntry) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{21}
}

func (x *NextPrepareEntry) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *NextPrepareEntry) GetFromAction() string {
	if x != nil && x.FromAction != nil {
		return *x.FromAction
	}
	return ""
}

func (x *NextPrepareEntry) GetFromState() string {
	if x != nil && x.FromState != nil {
		return *x.FromState
	}
	return ""
}

func (x *NextPrepareEntry) GetFromLiteral() *structpb.Value {
	if x != nil {
		return x.FromLiteral
	}
	return nil
}

type RouteModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Match         []*MatchArm            `protobuf:"bytes,2,rep,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteModel) Reset() {
	*x = RouteModel{}
	mi := &file_turnout_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteModel) ProtoMessage() {}

func (x *RouteModel) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteModel.ProtoReflect.Descriptor instead.
func (*RouteModel) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{22}
}

func (x *RouteModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteModel) GetMatch() []*MatchArm {
	if x != nil {
		return x.Match
	}
	return nil
}

type MatchArm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// patterns holds raw pattern strings. "_" is fallback; "scene.action" or
	// "scene.*.action[.action...]" are path forms. Multiple entries are OR-joined.
	Patterns      []string `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Target        string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchArm) Reset() {
	*x = MatchArm{}
	mi := &file_turnout_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchArm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchArm) ProtoMessage() {}

func (x *MatchArm) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchArm.ProtoReflect.Descriptor instead.
func (*MatchArm) Descriptor() ([]byte, []int) {
	return file_turnout_model_proto_rawDescGZIP(), []int{23}
}

func (x *MatchArm) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *MatchArm) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_turnout_model_proto protoreflect.FileDescriptor

const file_turnout_model_proto_rawDesc = "" +
	"\n" +
	"\x13turnout-model.proto\x12\x10turnout.model.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xab\x01\n" +
	"\tTurnModel\x122\n" +
	"\x05state\x18\x01 \x01(\v2\x1c.turnout.model.v1.StateModelR\x05state\x124\n" +
	"\x06scenes\x18\x02 \x03(\v2\x1c.turnout.model.v1.SceneBlockR\x06scenes\x124\n" +
	"\x06routes\x18\x03 \x03(\v2\x1c.turnout.model.v1.RouteModelR\x06routes\"N\n" +
	"\n" +
	"StateModel\x12@\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2 .turnout.model.v1.NamespaceModelR\n" +
	"namespaces\"Z\n" +
	"\x0eNamespaceModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06fields\x18\x02 \x03(\v2\x1c.turnout.model.v1.FieldModelR\x06fields\"b\n" +
	"\n" +
	"FieldModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xb0\x01\n" +
	"\n" +
	"SceneBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rentry_actions\x18\x02 \x03(\tR\fentryActions\x12$\n" +
	"\vnext_policy\x18\x03 \x01(\tH\x00R\n" +
	"nextPolicy\x88\x01\x01\x127\n" +
	"\aactions\x18\x04 \x03(\v2\x1d.turnout.model.v1.ActionModelR\aactionsB\x0e\n" +
	"\f_next_policy\"\x94\x02\n" +
	"\vActionModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\acompute\x18\x02 \x01(\v2\x1e.turnout.model.v1.ComputeModelR\acompute\x128\n" +
	"\aprepare\x18\x03 \x03(\v2\x1e.turnout.model.v1.PrepareEntryR\aprepare\x122\n" +
	"\x05merge\x18\x04 \x03(\v2\x1c.turnout.model.v1.MergeEntryR\x05merge\x12\x18\n" +
	"\apublish\x18\x05 \x03(\tR\apublish\x123\n" +
	"\x04next\x18\x06 \x03(\v2\x1f.turnout.model.v1.NextRuleModelR\x04next\"S\n" +
	"\fComputeModel\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12/\n" +
	"\x04prog\x18\x02 \x01(\v2\x1b.turnout.model.v1.ProgModelR\x04prog\"[\n" +
	"\tProgModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\bbindings\x18\x02 \x03(\v2\x1e.turnout.model.v1.BindingModelR\bbindings\"\x95\x01\n" +
	"\fBindingModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12/\n" +
	"\x04expr\x18\x04 \x01(\v2\x1b.turnout.model.v1.ExprModelR\x04expr\"\xa4\x01\n" +
	"\tExprModel\x127\n" +
	"\acombine\x18\x01 \x01(\v2\x1d.turnout.model.v1.CombineExprR\acombine\x12.\n" +
	"\x04pipe\x18\x02 \x01(\v2\x1a.turnout.model.v1.PipeExprR\x04pipe\x12.\n" +
	"\x04cond\x18\x03 \x01(\v2\x1a.turnout.model.v1.CondExprR\x04cond\"M\n" +
	"\vCombineExpr\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.turnout.model.v1.ArgModelR\x04args\"q\n" +
	"\bPipeExpr\x123\n" +
	"\x06params\x18\x01 \x03(\v2\x1b.turnout.model.v1.PipeParamR\x06params\x120\n" +
	"\x05steps\x18\x02 \x03(\v2\x1a.turnout.model.v1.PipeStepR\x05steps\"M\n" +
	"\tPipeParam\x12\x1d\n" +
	"\n" +
	"param_name\x18\x01 \x01(\tR\tparamName\x12!\n" +
	"\fsource_ident\x18\x02 \x01(\tR\vsourceIdent\"J\n" +
	"\bPipeStep\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.turnout.model.v1.ArgModelR\x04args\"\xb1\x01\n" +
	"\bCondExpr\x128\n" +
	"\tcondition\x18\x01 \x01(\v2\x1a.turnout.model.v1.ArgModelR\tcondition\x12.\n" +
	"\x04then\x18\x02 \x01(\v2\x1a.turnout.model.v1.ArgModelR\x04then\x12;\n" +
	"\velse_branch\x18\x03 \x01(\v2\x1a.turnout.model.v1.ArgModelR\n" +
	"elseBranch\"\xeb\x01\n" +
	"\bArgModel\x12\x15\n" +
	"\x03ref\x18\x01 \x01(\tH\x00R\x03ref\x88\x01\x01\x12(\n" +
	"\x03lit\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x03lit\x12\x1e\n" +
	"\bfunc_ref\x18\x03 \x01(\tH\x01R\afuncRef\x88\x01\x01\x12\x1e\n" +
	"\bstep_ref\x18\x04 \x01(\x05H\x02R\astepRef\x88\x01\x01\x12<\n" +
	"\ttransform\x18\x05 \x01(\v2\x1e.turnout.model.v1.TransformArgR\ttransformB\x06\n" +
	"\x04_refB\v\n" +
	"\t_func_refB\v\n" +
	"\t_step_ref\"0\n" +
	"\fTransformArg\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x0e\n" +
	"\x02fn\x18\x02 \x01(\tR\x02fn\"\x8b\x01\n" +
	"\fPrepareEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12\"\n" +
	"\n" +
	"from_state\x18\x02 \x01(\tH\x00R\tfromState\x88\x01\x01\x12 \n" +
	"\tfrom_hook\x18\x03 \x01(\tH\x01R\bfromHook\x88\x01\x01B\r\n" +
	"\v_from_stateB\f\n" +
	"\n" +
	"_from_hook\"A\n" +
	"\n" +
	"MergeEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12\x19\n" +
	"\bto_state\x18\x02 \x01(\tR\atoState\"\xa3\x01\n" +
	"\rNextRuleModel\x12<\n" +
	"\acompute\x18\x01 \x01(\v2\".turnout.model.v1.NextComputeModelR\acompute\x12<\n" +
	"\aprepare\x18\x02 \x03(\v2\".turnout.model.v1.NextPrepareEntryR\aprepare\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"a\n" +
	"\x10NextComputeModel\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12/\n" +
	"\x04prog\x18\x02 \x01(\v2\x1b.turnout.model.v1.ProgModelR\x04prog\"\xd0\x01\n" +
	"\x10NextPrepareEntry\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12$\n" +
	"\vfrom_action\x18\x02 \x01(\tH\x00R\n" +
	"fromAction\x88\x01\x01\x12\"\n" +
	"\n" +
	"from_state\x18\x03 \x01(\tH\x01R\tfromState\x88\x01\x01\x129\n" +
	"\ffrom_literal\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\vfromLiteralB\x0e\n" +
	"\f_from_actionB\r\n" +
	"\v_from_state\"N\n" +
	"\n" +
	"RouteModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05match\x18\x02 \x03(\v2\x1a.turnout.model.v1.MatchArmR\x05match\">\n" +
	"\bMatchArm\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06targetBIZGgithub.com/kozmof/turnout/packages/go/converter/internal/emit/turnoutpbb\x06proto3"

var (
	file_turnout_model_proto_rawDescOnce sync.Once
	file_turnout_model_proto_rawDescData []byte
)

func file_turnout_model_proto_rawDescGZIP() []byte {
	file_turnout_model_proto_rawDescOnce.Do(func() {
		file_turnout_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_turnout_model_proto_rawDesc), len(file_turnout_model_proto_rawDesc)))
	})
	return file_turnout_model_proto_rawDescData
}

var file_turnout_model_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_turnout_model_proto_goTypes = []any{
	(*TurnModel)(nil),        // 0: turnout.model.v1.TurnModel
	(*StateModel)(nil),       // 1: turnout.model.v1.StateModel
	(*NamespaceModel)(nil),   // 2: turnout.model.v1.NamespaceModel
	(*FieldModel)(nil),       // 3: turnout.model.v1.FieldModel
	(*SceneBlock)(nil),       // 4: turnout.model.v1.SceneBlock
	(*ActionModel)(nil),      // 5: turnout.model.v1.ActionModel
	(*ComputeModel)(nil),     // 6: turnout.model.v1.ComputeModel
	(*ProgModel)(nil),        // 7: turnout.model.v1.ProgModel
	(*BindingModel)(nil),     // 8: turnout.model.v1.BindingModel
	(*ExprModel)(nil),        // 9: turnout.model.v1.ExprModel
	(*CombineExpr)(nil),      // 10: turnout.model.v1.CombineExpr
	(*PipeExpr)(nil),         // 11: turnout.model.v1.PipeExpr
	(*PipeParam)(nil),        // 12: turnout.model.v1.PipeParam
	(*PipeStep)(nil),         // 13: turnout.model.v1.PipeStep
	(*CondExpr)(nil),         // 14: turnout.model.v1.CondExpr
	(*ArgModel)(nil),         // 15: turnout.model.v1.ArgModel
	(*TransformArg)(nil),     // 16: turnout.model.v1.TransformArg
	(*PrepareEntry)(nil),     // 17: turnout.model.v1.PrepareEntry
	(*MergeEntry)(nil),       // 18: turnout.model.v1.MergeEntry
	(*NextRuleModel)(nil),    // 19: turnout.model.v1.NextRuleModel
	(*NextComputeModel)(nil), // 20: turnout.model.v1.NextComputeModel
	(*NextPrepareEntry)(nil), // 21: turnout.model.v1.NextPrepareEntry
	(*RouteModel)(nil),       // 22: turnout.model.v1.RouteModel
	(*MatchArm)(nil),         // 23: turnout.model.v1.MatchArm
	(*structpb.Value)(nil),   // 24: google.protobuf.Value
}
var file_turnout_model_proto_depIdxs = []int32{
	1,  // 0: turnout.model.v1.TurnModel.state:type_name -> turnout.model.v1.StateModel
	4,  // 1: turnout.model.v1.TurnModel.scenes:type_name -> turnout.model.v1.SceneBlock
	22, // 2: turnout.model.v1.TurnModel.routes:type_name -> turnout.model.v1.RouteModel
	2,  // 3: turnout.model.v1.StateModel.namespaces:type_name -> turnout.model.v1.NamespaceModel
	3,  // 4: turnout.model.v1.NamespaceModel.fields:type_name -> turnout.model.v1.FieldModel
	24, // 5: turnout.model.v1.FieldModel.value:type_name -> google.protobuf.Value
	5,  // 6: turnout.model.v1.SceneBlock.actions:type_name -> turnout.model.v1.ActionModel
	6,  // 7: turnout.model.v1.ActionModel.compute:type_name -> turnout.model.v1.ComputeModel
	17, // 8: turnout.model.v1.ActionModel.prepare:type_name -> turnout.model.v1.PrepareEntry
	18, // 9: turnout.model.v1.ActionModel.merge:type_name -> turnout.model.v1.MergeEntry
	19, // 10: turnout.model.v1.ActionModel.next:type_name -> turnout.model.v1.NextRuleModel
	7,  // 11: turnout.model.v1.ComputeModel.prog:type_name -> turnout.model.v1.ProgModel
	8,  // 12: turnout.model.v1.ProgModel.bindings:type_name -> turnout.model.v1.BindingModel
	24, // 13: turnout.model.v1.BindingModel.value:type_name -> google.protobuf.Value
	9,  // 14: turnout.model.v1.BindingModel.expr:type_name -> turnout.model.v1.ExprModel
	10, // 15: turnout.model.v1.ExprModel.combine:type_name -> turnout.model.v1.CombineExpr
	11, // 16: turnout.model.v1.ExprModel.pipe:type_name -> turnout.model.v1.PipeExpr
	14, // 17: turnout.model.v1.ExprModel.cond:type_name -> turnout.model.v1.CondExpr
	15, // 18: turnout.model.v1.CombineExpr.args:type_name -> turnout.model.v1.ArgModel
	12, // 19: turnout.model.v1.PipeExpr.params:type_name -> turnout.model.v1.PipeParam
	13, // 20: turnout.model.v1.PipeExpr.steps:type_name -> turnout.model.v1.PipeStep
	15, // 21: turnout.model.v1.PipeStep.args:type_name -> turnout.model.v1.ArgModel
	15, // 22: turnout.model.v1.CondExpr.condition:type_name -> turnout.model.v1.ArgModel
	15, // 23: turnout.model.v1.CondExpr.then:type_name -> turnout.model.v1.ArgModel
	15, // 24: turnout.model.v1.CondExpr.else_branch:type_name -> turnout.model.v1.ArgModel
	24, // 25: turnout.model.v1.ArgModel.lit:type_name -> google.protobuf.Value
	16, // 26: turnout.model.v1.ArgModel.transform:type_name -> turnout.model.v1.TransformArg
	20, // 27: turnout.model.v1.NextRuleModel.compute:type_name -> turnout.model.v1.NextComputeModel
	21, // 28: turnout.model.v1.NextRuleModel.prepare:type_name -> turnout.model.v1.NextPrepareEntry
	7,  // 29: turnout.model.v1.NextComputeModel.prog:type_name -> turnout.model.v1.ProgModel
	24, // 30: turnout.model.v1.NextPrepareEntry.from_literal:type_name -> google.protobuf.Value
	23, // 31: turnout.model.v1.RouteModel.match:type_name -> turnout.model.v1.MatchArm
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_turnout_model_proto_init() }
func file_turnout_model_proto_init() {
	if File_turnout_model_proto != nil {
		return
	}
	file_turnout_model_proto_msgTypes[4].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[15].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[17].OneofWrappers = []any{}
	file_turnout_model_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_turnout_model_proto_rawDesc), len(file_turnout_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turnout_model_proto_goTypes,
		DependencyIndexes: file_turnout_model_proto_depIdxs,
		MessageInfos:      file_turnout_model_proto_msgTypes,
	}.Build()
	File_turnout_model_proto = out.File
	file_turnout_model_proto_goTypes = nil
	file_turnout_model_proto_depIdxs = nil
}
